In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Initialize a Session object
session = requests.Session()

# Base URL of the site to scrape
base_url = 'https://fr.trustpilot.com/review/carbrain.com?page='

# List to hold all the scraped data
reviews_data = []

# Function to process a soup object and extract data
def extract_data(soup):
    titles = soup.find_all('h2', class_='typography_heading-s__f7029 typography_appearance-default__AAY17')
    reviews = soup.find_all('p', class_='typography_body-l__KUYFJ typography_appearance-default__AAY17 typography_color-black__5LYEn')
    dates = soup.find_all('p', class_='typography_body-m__xgxZ_ typography_appearance-default__AAY17')
    ratings = soup.find_all('div', class_='star-rating_starRating__4rrcf star-rating_medium__iN6Ty')[1:]

    for title, review, date, rating in zip(titles, reviews, dates, ratings):
        img = rating.find('img')
        if img and img.has_attr('alt'):
            rating_text = img['alt']
            reviews_data.append({
                'Title': title.get_text(strip=True),
                'Review': review.get_text(strip=True),
                'Date': date.get_text(strip=True),
                'Rate': rating_text
            })

# Loop through the range of page numbers you want to scrape
for page_num in range(1, 288):  # Modify as needed
    url = f"{base_url}{page_num}"
    
    response = session.get(url)
    
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        extract_data(soup)
    else:
        print(f"Failed to retrieve page {page_num}: Status code {response.status_code}")

# Convert to DataFrame
df = pd.DataFrame(reviews_data)

In [19]:
df

,Title,Review,Date,Rate
0,This was the most awesome and efficient…,The most awesome & efficient service EVER!! Le...,Date de l'expérience:17 avril 2024,Noté 5 sur 5 étoiles
1,Was offered a bit more than other…,Was offered a bit more than other companies an...,Date de l'expérience:24 avril 2024,Noté 4 sur 5 étoiles
2,How are you going to say y'all buy any…,How are you going to say y'all buy any car whe...,Date de l'expérience:25 avril 2024,Noté 1 sur 5 étoiles
3,Excellent service!,Very streamlined and efficient process. Christ...,Date de l'expérience:25 avril 2024,Noté 5 sur 5 étoiles
4,From Elwood IL very professional …,I live in Elwood IL just about a hour south of...,Date de l'expérience:25 avril 2024,Noté 5 sur 5 étoiles
...,...,...,...,...
5071,Honest and reliable!,The entire Process was pretty seamless. I had...,Date de l'expérience:07 août 2017,Noté 5 sur 5 étoiles
5072,The entire Process was pretty seamless.,Great company all was as they stated very happy.,Date de l'expérience:07 août 2017,Noté 4 sur 5 étoiles
5073,rate,I would recommend CarBrain to others because t...,Date de l'expérience:04 août 2017,Noté 5 sur 5 étoiles
5074,Caring employees...,"It was fast, easy, and very convenient. The se...",Date de l'expérience:04 août 2017,Noté 5 sur 5 étoiles
5075,2 thumbs up!,Nancy was extremely helpful throughout the ent...,Date de l'expérience:02 août 2017,Noté 5 sur 5 étoiles

In [20]:
df['Date'] = df['Date'].str.extract(r'Date de l\'expérience:(.+)')
df['Rate'] = df['Rate'].str.extract(r'(\d+)').astype(int)

In [21]:
df

,Title,Review,Date,Rate
0,This was the most awesome and efficient…,The most awesome & efficient service EVER!! Le...,17 avril 2024,5
1,Was offered a bit more than other…,Was offered a bit more than other companies an...,24 avril 2024,4
2,How are you going to say y'all buy any…,How are you going to say y'all buy any car whe...,25 avril 2024,1
3,Excellent service!,Very streamlined and efficient process. Christ...,25 avril 2024,5
4,From Elwood IL very professional …,I live in Elwood IL just about a hour south of...,25 avril 2024,5
...,...,...,...,...
5071,Honest and reliable!,The entire Process was pretty seamless. I had...,07 août 2017,5
5072,The entire Process was pretty seamless.,Great company all was as they stated very happy.,07 août 2017,4
5073,rate,I would recommend CarBrain to others because t...,04 août 2017,5
5074,Caring employees...,"It was fast, easy, and very convenient. The se...",04 août 2017,5
5075,2 thumbs up!,Nancy was extremely helpful throughout the ent...,02 août 2017,5

In [1]:
df.to_csv('text_data.csv', sep=',', decimal='.', index=None)

NameError: name 'df' is not defined